// ── Phytochemical database ────────────────────────────────────────────────────

export interface Phytochemical {
  id: string
  name: string
  iupac: string
  cid: number
  smiles: string
  formula: string
  mw: number
  logP: number
  hbd: number
  hba: number
  tpsa: number
  rotatable: number
  class: string
  plantPart: string
  activity: ("antioxidant" | "pro-apoptotic" | "anti-proliferative" | "hepatoprotective" | "anti-invasive" | "immunomodulatory")[]
  potency: "high" | "moderate" | "low"
  color: string
  description: string
}

export const PHYTOCHEMICALS: Phytochemical[] = [
  {
    id: "quercetin",
    name: "Quercetin",
    iupac: "2-(3,4-dihydroxyphenyl)-3,5,7-trihydroxychromen-4-one",
    cid: 5280343,
    smiles: "O=c1c(O)c(-c2ccc(O)c(O)c2)oc2cc(O)cc(O)c12",
    formula: "C₁₅H₁₀O₇",
    mw: 302.24,
    logP: -1.75,
    hbd: 5, hba: 7, tpsa: 131.4, rotatable: 1,
    class: "Flavonol",
    plantPart: "Leaves, stems (primary compound)",
    activity: ["antioxidant", "pro-apoptotic", "anti-proliferative", "hepatoprotective"],
    potency: "high",
    color: "#00d4aa",
    description: "Primary bioactive flavonoid in Sampasampalukan. Inhibits YAP1–TEAD4, activates BAX/caspase cascade, and upregulates Nrf2 antioxidant defense. Nanoencapsulation improves bioavailability 3.8×.",
  },
  {
    id: "rutin",
    name: "Rutin",
    iupac: "2-(3,4-dihydroxyphenyl)-5,7-dihydroxy-3-[α-L-rhamnopyranosyl-(1→6)-β-D-glucopyranosyloxy]chromen-4-one",
    cid: 5280805,
    smiles: "O=c1c(OC2OC(CO)C(O)C(O)C2OC2OC(C)C(O)C(O)C2)c(-c2ccc(O)c(O)c2)oc2cc(O)cc(O)c12",
    formula: "C₂₇H₃₀O₁₆",
    mw: 610.52,
    logP: -1.26,
    hbd: 10, hba: 16, tpsa: 269.4, rotatable: 5,
    class: "Flavonoid glycoside",
    plantPart: "Leaves, fruits",
    activity: ["antioxidant", "anti-proliferative", "hepatoprotective"],
    potency: "high",
    color: "#4fc3f7",
    description: "Quercetin-3-rutinoside. Stronger binding than free quercetin due to sugar moiety enlarging the contact surface. Excellent hepatoprotective profile — reduces ALT/AST enzyme levels in liver injury models.",
  },
  {
    id: "luteolin",
    name: "Luteolin",
    iupac: "2-(3,4-dihydroxyphenyl)-5,7-dihydroxy-4H-chromen-4-one",
    cid: 5280445,
    smiles: "O=c1cc(-c2ccc(O)c(O)c2)oc2cc(O)cc(O)c12",
    formula: "C₁₅H₁₀O₆",
    mw: 286.24,
    logP: -0.72,
    hbd: 4, hba: 6, tpsa: 111.1, rotatable: 1,
    class: "Flavone",
    plantPart: "Whole plant",
    activity: ["antioxidant", "anti-proliferative", "anti-invasive"],
    potency: "high",
    color: "#a78bfa",
    description: "Flavone structurally similar to quercetin but without 3-OH group. Inhibits EGFR/mTOR signaling and MMP-9 matrix metalloproteinase, suppressing HCC invasion and migration.",
  },
  {
    id: "kaempferol",
    name: "Kaempferol",
    iupac: "3,5,7-trihydroxy-2-(4-hydroxyphenyl)-4H-chromen-4-one",
    cid: 5280863,
    smiles: "O=c1c(O)c(-c2ccc(O)cc2)oc2cc(O)cc(O)c12",
    formula: "C₁₅H₁₀O₆",
    mw: 286.24,
    logP: -0.51,
    hbd: 4, hba: 6, tpsa: 111.1, rotatable: 1,
    class: "Flavonol",
    plantPart: "Leaves",
    activity: ["antioxidant", "anti-proliferative", "pro-apoptotic"],
    potency: "moderate",
    color: "#fbbf24",
    description: "Flavonol with 4'-mono-hydroxyl B-ring (vs quercetin's 3',4'-diOH). Moderate HCC cytotoxicity — inhibits Cyclin D1 and induces G2/M arrest. Synergistic effect when combined with quercetin.",
  },
  {
    id: "ellagicacid",
    name: "Ellagic Acid",
    iupac: "2,3,7,8-tetrahydroxy-chromeno[5,4,3-cde]chromene-5,10-dione",
    cid: 5281855,
    smiles: "O=c1oc2c(O)c(O)cc3c(=O)oc4cc(O)c(O)cc4c1c23",
    formula: "C₁₄H₆O₈",
    mw: 302.19,
    logP: -1.89,
    hbd: 4, hba: 8, tpsa: 147.1, rotatable: 0,
    class: "Polyphenol / Tannin",
    plantPart: "Fruits, leaves",
    activity: ["antioxidant", "anti-proliferative", "pro-apoptotic"],
    potency: "high",
    color: "#fb923c",
    description: "Planar polycyclic structure enables excellent π-stacking with aromatic residues in protein binding pockets. Strong Nrf2 activator and DNA topoisomerase II inhibitor — dual mechanism against HCC.",
  },
  {
    id: "gallicacid",
    name: "Gallic Acid",
    iupac: "3,4,5-trihydroxybenzoic acid",
    cid: 370,
    smiles: "OC(=O)c1cc(O)c(O)c(O)c1",
    formula: "C₇H₆O₅",
    mw: 170.12,
    logP: 0.70,
    hbd: 4, hba: 5, tpsa: 97.3, rotatable: 1,
    class: "Phenolic acid",
    plantPart: "Whole plant",
    activity: ["antioxidant", "pro-apoptotic"],
    potency: "moderate",
    color: "#34d399",
    description: "Simple phenolic acid; precursor to ellagitannins. Moderate HCC activity via ROS induction and caspase activation. Strong free radical scavenging (DPPH IC₅₀ 3.2 µM). Low MW aids membrane penetration.",
  },
  {
    id: "corilagin",
    name: "Corilagin",
    iupac: "[(1R,2R,3S,4S,5S,6R)-2-{[(2R,3R,4S,5R)-3,4,5-trihydroxy-6-oxotetrahydro-2H-pyran-2-yl]oxy}-3,4,5,6-tetrahydroxycyclohexyl] 3,4-dihydroxy-5-{[(Z)- ... }benzoate",
    cid: 73568,
    smiles: "O=C(OC1OC(OC(=O)c2cc(O)c(O)c(O)c2)C(O)C(O)C1O)c1cc(O)c(O)c(O)c1",
    formula: "C₂₇H₂₂O₁₈",
    mw: 634.44,
    logP: -4.21,
    hbd: 11, hba: 18, tpsa: 320.5, rotatable: 7,
    class: "Ellagitannin",
    plantPart: "Whole plant (major tannin)",
    activity: ["anti-proliferative", "hepatoprotective", "pro-apoptotic", "immunomodulatory"],
    potency: "high",
    color: "#f472b6",
    description: "Signature ellagitannin of Phyllanthus niruri. High MW enables multiple simultaneous interactions in large protein binding sites. Strong hepatoprotective effect — reduces CCl₄-induced hepatocyte damage. HCC IC₅₀ ~12 µM.",
  },
  {
    id: "geraniin",
    name: "Geraniin",
    iupac: "Geraniin (complex ellagitannin)",
    cid: 119084,
    smiles: "O=C1OC(OC(=O)c2cc(O)c(O)c(O)c2)C(OC(=O)c2cc(O)c(O)c(O)c2)C(OC(=O)c2cc(O)c(O)c(O)c2)C1O",
    formula: "C₄₁H₂₈O₂₇",
    mw: 952.64,
    logP: -6.82,
    hbd: 14, hba: 27, tpsa: 482.1, rotatable: 10,
    class: "Ellagitannin",
    plantPart: "Leaves (abundant)",
    activity: ["antioxidant", "anti-proliferative", "hepatoprotective", "immunomodulatory"],
    potency: "high",
    color: "#e879f9",
    description: "Largest and most structurally complex compound in Sampasampalukan. Multiple galloyl groups enable exceptionally strong multi-point protein binding. Potent HCC activity — targets Bcl-2, EGFR, and VEGFR2 simultaneously.",
  },
  {
    id: "phyllanthin",
    name: "Phyllanthin",
    iupac: "(−)-Phyllanthin",
    cid: 9908089,
    smiles: "COc1cc(CC(COc2cc(OC)c(OC)cc2CC)OC)ccc1OC",
    formula: "C₂₄H₃₄O₆",
    mw: 418.52,
    logP: 3.42,
    hbd: 0, hba: 6, tpsa: 64.6, rotatable: 10,
    class: "Lignan",
    plantPart: "Whole plant (marker compound)",
    activity: ["hepatoprotective", "anti-proliferative", "anti-invasive"],
    potency: "moderate",
    color: "#06b6d4",
    description: "Lignan and chemotaxonomic marker of Phyllanthus species. High logP (3.42) gives good membrane permeability. Hepatoprotective — inhibits CYP2E1-mediated hepatotoxicity. Moderate HCC anti-proliferative activity via cell cycle arrest.",
  },
  {
    id: "hypophyllanthin",
    name: "Hypophyllanthin",
    iupac: "(−)-Hypophyllanthin",
    cid: 9979682,
    smiles: "COc1cc(CC(COc2cc(OC)c(OC)cc2CC)OC)ccc1OC",
    formula: "C₂₄H₃₄O₇",
    mw: 434.52,
    logP: 2.94,
    hbd: 0, hba: 7, tpsa: 73.5, rotatable: 10,
    class: "Lignan",
    plantPart: "Whole plant (co-marker)",
    activity: ["hepatoprotective", "anti-proliferative"],
    potency: "moderate",
    color: "#84cc16",
    description: "Structural analog of phyllanthin with additional hydroxyl. Hepatoprotective properties demonstrated in HBV model studies — reduces HBsAg secretion in PLC/PRF/5 cells. Synergistic with quercetin in combination treatments.",
  },
  {
    id: "astragalin",
    name: "Astragalin",
    iupac: "Kaempferol-3-O-glucoside",
    cid: 5318767,
    smiles: "O=c1c(OC2OC(CO)C(O)C(O)C2O)c(-c2ccc(O)cc2)oc2cc(O)cc(O)c12",
    formula: "C₂₁H₂₀O₁₁",
    mw: 448.38,
    logP: -0.88,
    hbd: 7, hba: 11, tpsa: 190.3, rotatable: 3,
    class: "Flavonoid glycoside",
    plantPart: "Leaves",
    activity: ["antioxidant", "anti-proliferative", "anti-invasive"],
    potency: "moderate",
    color: "#f97316",
    description: "Kaempferol glucoside with improved water solubility. Anti-invasive properties via MMP-9 inhibition. Induces autophagy in HepG2 cells as a complementary anti-cancer mechanism alongside apoptosis.",
  },
  {
    id: "betasitosterol",
    name: "β-Sitosterol",
    iupac: "(3S,8S,9S,10R,13R,14S,17R)-17-[(2R,5R)-5-ethyl-6-methylheptan-2-yl]-10,13-dimethyl-2,3,4,7,8,9,10,11,12,13,14,15,16,17-tetradecahydro-1H-cyclopenta[a]phenanthren-3-ol",
    cid: 222284,
    smiles: "CCC(CCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C)C",
    formula: "C₂₉H₅₀O",
    mw: 414.71,
    logP: 8.08,
    hbd: 1, hba: 1, tpsa: 20.2, rotatable: 7,
    class: "Phytosterol",
    plantPart: "Whole plant",
    activity: ["anti-proliferative", "immunomodulatory"],
    potency: "moderate",
    color: "#64748b",
    description: "Plant sterol structurally similar to cholesterol. High logP enables membrane insertion and disruption of lipid rafts in cancer cells. Inhibits androgen receptor pathway in hepatocellular carcinoma. Moderate IC₅₀ range.",
  },
  {
    id: "niranthin",
    name: "Niranthin",
    iupac: "Niranthin",
    cid: 12303734,
    smiles: "COc1cc([C@@H]2OC[C@@H]3[C@@H]2CC(=C)[C@@H]3Cc2ccc(OC)c(OC)c2)ccc1OC",
    formula: "C₂₄H₃₂O₆",
    mw: 416.50,
    logP: 3.21,
    hbd: 0, hba: 6, tpsa: 64.6, rotatable: 6,
    class: "Lignan",
    plantPart: "Roots, stems",
    activity: ["hepatoprotective", "anti-proliferative"],
    potency: "moderate",
    color: "#a3e635",
    description: "Cyclolignan specific to Phyllanthus genus. Hepatoprotective via HBV DNA replication inhibition — relevant for HBV-associated HCC. Moderate cytotoxicity with preferential activity in HBV+ lines (HepG2, Hep3B).",
  },
  {
    id: "securinine",
    name: "Securinine",
    iupac: "(3aR,7R,12bS)-3a,4,5,7,8,9,10,12b-octahydro-7-methyl-3H-pyrano[4,3-b][1]benzoxepine",
    cid: 10010,
    smiles: "O=C1OCC=C2CCCCN3CC=CC(=C1)[C@H]23",
    formula: "C₁₃H₁₅NO₂",
    mw: 217.27,
    logP: 0.86,
    hbd: 0, hba: 3, tpsa: 29.5, rotatable: 0,
    class: "Alkaloid",
    plantPart: "Whole plant",
    activity: ["anti-proliferative", "immunomodulatory", "pro-apoptotic"],
    potency: "moderate",
    color: "#e11d48",
    description: "Unique securinega alkaloid. GABA-A receptor antagonist that paradoxically activates immune surveillance against tumors. Induces differentiation in HCC cells at sub-cytotoxic doses — novel anti-HCC mechanism distinct from other compounds.",
  },
]

// ── Protein targets (shared with docking) ─────────────────────────────────────

export const PROTEIN_IDS = [
  "YAP1", "BAX", "BCL2", "CASP3", "NRF2", "LATS1",
  "TP53", "EGFR", "CASP9", "MMP9", "MTOR", "CCND1",
]

